package com.movie.six.coding.test

data class MovieObject(
    val chiInfoDict: ChiInfoDict,
    val chiLanguage: String,
    val chiName: String,
    val chiSynopsis: String,
    val commentCount: Int,
    val commentDate: String,
    val dbTrailerUrl: String,
    val duration: Int,
    val engNormalAltNames: String,
    val favCount: Int,
    val favourite: Boolean,
    val id: Int,
    val infoDict: InfoDict,
    val interestingness: Int,
    val interestingnessComing: Int,
    val isCommentable: Boolean,
    val isOpenMonth: Boolean,
    val isShowPromoIcon: Boolean,
    val language: String,
    val multitrailers: List<String>,
    val name: String,
    val notification: Boolean,
    val openDate: String,
    val pagination: Pagination,
    val rateCount: Int,
    val rating: Int,
    val screenShots: List<String>,
    val status: Int,
    val synopsis: String,
    val thumbnail: String,
    val trailerUrl: String,
    val uuid: String
)